"""Add is_superuser to user table

Revision ID: 082660dbd0b1
Revises: 1005c550d415
Create Date: 2023-03-06 22:01:51.953410

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "082660dbd0b1"
down_revision = "1005c550d415"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_superuser")
    # ### end Alembic commands ###
