name: Linters

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Check with Flake8
      run: poetry run flake8

    - name: Format with Black
      run: poetry run black --check --diff .

    - name: Check import order with isort
      run: poetry run isort --check-only --diff .
